version: '3.8'

services:
  users:
    build: ./services/users
    ports:
      - "8081:8081"
    environment:
      - LOG_LEVEL=info
    networks:
      - gofed-network

  products:
    build: ./services/products
    ports:
      - "8082:8082"
    environment:
      - LOG_LEVEL=info
    networks:
      - gofed-network

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - users
      - products
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=4000
      - USERS_SERVICE_URL=http://users:8081/query
      - PRODUCTS_SERVICE_URL=http://products:8082/query
    networks:
      - gofed-network

networks:
  gofed-network:
    driver: bridge 