// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Category    string  `json:"category"`
	Owner       *User   `json:"owner"`
}

type Query struct {
}

type SemaphoreStats struct {
	Max       int `json:"max"`
	Current   int `json:"current"`
	Available int `json:"available"`
	Usage     int `json:"usage"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
